### ISSUE TITLE
ordering problem in phybreakdata

### ISSUE THREAD

**Issue by gtonkinhill** [donkeyshot/phybreak#4]
I think there is a minor bug that causes problems when different hosts share the same sampling times. I think line 122 in phybreakdata needs to be adjusted from

`
sapply(allhosts, function(x) allfirsttimes[which(min(sample.times[host.names == 
                                                                      x]) == sample.times)[1]] <<- TRUE)
`

to

`
sapply(allhosts, function(x) allfirsttimes[which(min(sample.times[host.names == 
                                                                      x]) == sample.times & (host.names == 
                                                                                               x))[1]] <<- TRUE)
`

as the first condition `min(sample.times[host.names == x]) == sample.times` may match with a different host that shares the same sampling time. This leads to cryptic error messages later on when sampling times precede infection times.

**Comment by donkeyshot** [comment]
Thanks Gerry! I'm sorry about that. Funny, I just encountered this myself as well last Friday. I'll fix it this week. In the meantime, as a not so pretty 'workaround' you may enter your sampling times as numeric and add a tiny fraction to one of the conflicting times.Thank you for using my package, I'd be happy to get more feedback and suggestions.
CheersDon
-------- Oorspronkelijk bericht --------Van: Gerry Tonkin-Hill <notifications@github.com> Datum: 16-10-17  16:23  (GMT+01:00) Aan: donkeyshot/phybreak <phybreak@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Onderwerp: [donkeyshot/phybreak] ordering problem in phybreakdata (#4) 
I think there is a minor bug that causes problems when different hosts share the same sampling times. I think line 122 in phybreakdata needs to be adjusted from
sapply(allhosts, function(x) allfirsttimes[which(min(sample.times[host.names == x]) == sample.times)[1]] <<- TRUE)
to
sapply(allhosts, function(x) allfirsttimes[which(min(sample.times[host.names == x]) == sample.times & (host.names == x))[1]] <<- TRUE)
as the first condition min(sample.times[host.names == x]) == sample.times may match with a different host that shares the same sampling time. This leads to cryptic error messages later on when sampling times precede infection times.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/donkeyshot/phybreak","title":"donkeyshot/phybreak","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/donkeyshot/phybreak"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"ordering problem in phybreakdata (#4)"}],"action":{"name":"View Issue","url":"https://github.com/donkeyshot/phybreak/issues/4"}}}
